<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admins</name>
   <tag></tag>
   <elementGuidId>58456a0d-8e33-4090-9a06-1d4b78b6a7f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ACCOUNTS&quot;)/li[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ACCOUNTS&quot;]/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
