<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_edit_remove_checkbox</name>
   <tag></tag>
   <elementGuidId>08847c73-24ec-462d-9ae6-63c5f270cc23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
//input[@class='checkbox'][@value=&quot;${value}&quot;]/../parent::label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>
//input[@class='checkbox'][@value=&quot;${value}&quot;]/../parent::label</value>
   </webElementProperties>
</WebElementEntity>
