<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyadmincreated</name>
   <tag></tag>
   <elementGuidId>c76fc235-0318-40f6-828a-6347989c2339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[1]/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[1]/td[5]/a</value>
   </webElementProperties>
</WebElementEntity>
