<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExcludeFacilities</name>
   <tag></tag>
   <elementGuidId>1fdccb4d-a1b8-457d-828d-088d60d97f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;EXCLUSIONS&quot;]//*[contains(text(),&quot;${excludefacilities}&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
